Dockerfile: set FROM to v0.2.8 for updated entrypoint
wsbu/toolchain-linaro pull request #17
Opened 2018-10-17 17:08 UTC by pwalkr

https://github.com/wsbu/toolchain-native/pull/22

2018-10-17 17:38 UTC, DavidZemon commented
Please update `docker-linaro` script with a new tag name.

2018-10-17 17:45 UTC, pwalkr commented
> Please update `docker-linaro` script with a new tag name.

It's already using `:latest` - https://github.com/wsbu/toolchain-linaro/blob/master/docker-linaro
But I can remove the arbitrary `:4.9` tag here: https://github.com/wsbu/toolchain-linaro/blob/5f7c6e3/Dockerfile#L1

2018-10-17 17:47 UTC, DavidZemon commented
Yea, sorry - I didn't realize it wasn't use a tag. Can you add a tag? And yes... remove that silly comment please :)

2018-10-17 17:52 UTC, pwalkr commented
Care if I take out the whole Dockerfile header comment? It's an example just asking to get out of sync with docker-linaro script.

2018-10-17 18:11 UTC, DavidZemon commented
Nope, been thinking about that too. It was dropped in before that script existed.

2018-10-17 21:16 UTC, pwalkr commented
Bump - updated version in self-referencing script and removed redundant comment

2018-10-17 21:18 UTC, DavidZemon approved these changes

2018-10-18 12:51 UTC, mattcaron-redlion approved these changes

2018-10-19 18:08 UTC, pwalkr commented
One more bump... rebased back to 1.1.6, merge target is now `release-1` since master is off in v2 realm with ubuntu 18.04. Relates to new PR in toolchain-native: https://github.com/wsbu/toolchain-native/pull/23

2018-10-19 19:01 UTC, DavidZemon requested changes

2018-10-19 19:01 UTC, DavidZemon commented on Dockerfile
> +FROM pfw/toolchain-native-v0.1.6:c72d203
Will approve was this gets updated.

2018-10-19 19:43 UTC, pwalkr commented
Fix'd (removed my debug docker tag name)

2018-10-19 20:01 UTC, DavidZemon approved these changes

2018-10-19 20:03 UTC, mattcaron-redlion approved these changes

2018-10-19 20:10 UTC, merged